name: TestTask
on:
  repository_dispatch:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          method: ${{ on.repository_dispatch.client_payload.method }}
          body: ${{ toJson(on.repository_dispatch.client_payload.body) }}
          headers: ${{ toJson(on.repository_dispatch.client_payload.headers) }}
        run: |
          echo method: $method
          echo headers $headers
          echo body: $body